language: node_js
node_js:
- '0.10'
services:
- mongodb
before_script:
- npm install gulp -g
deploy:
  provider: heroku
  api_key:
    secure: yNgE0NqIUewmXddVOx6WS64EbBBbr9OwkpWDLQWugiH/eKGMqAGSlMsGcpiqC2tOR6M0tq0FINEcWBduGWs9OhFOY4ggFe+RSFnQgiAoKwzQLlla3v/vHA+SJ15xidENEWdrBfy4i66gn/j2jpWWcpgnY0gsaU6claJc+aHlbKE=
  app: pullup
  on:
    repo: larvalabs/pullup
git:
  depth: 10
