---
- name: ensure apt-get is up to date
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: ensure build-essential installed
  apt: pkg=build-essential state=present
  sudo: yes

- name: ensure git is installed
  apt: pkg=git state=present
  sudo: yes

- name: ensure curl is installed
  apt: pkg=curl state=present
  sudo: yes