- name: add apt-get key for mongo
  shell: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  sudo: yes

- name: add apt-get repository for latest mongo
  shell: echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | tee /etc/apt/sources.list.d/mongodb.list
  sudo: yes

- name: ensure apt-get is up to date with added dependencies
  apt: update_cache=yes
  sudo: yes

- name: install mongo
  apt: pkg=mongodb-10gen state=present
  sudo: yes